Import Libraries

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os

In [2]:
#import dataframe 
df_ords_merged = pd.read_pickle(r'/Users/samuelcallender/Documents/ Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged_updated.pkl')

In [3]:
#create a subset
df = df_ords_merged[:1000000]

In [4]:
df.shape

(1000000, 21)

In [5]:
df.head(10)

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,...,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,0,0,2539329,1,prior,1,2,8,NaN,196,...,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders
1,1,1,2398795,1,prior,2,3,7,15.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
2,2,2,473747,1,prior,3,3,12,21.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders
3,3,3,2254736,1,prior,4,4,7,29.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders
4,4,4,431534,1,prior,5,4,15,28.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders
5,5,5,3367565,1,prior,6,2,7,19.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders
6,6,6,550135,1,prior,7,1,9,20.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders
7,7,7,3108588,1,prior,8,1,14,14.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders
8,8,8,2295261,1,prior,9,1,16,0.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders
9,9,9,2550362,1,prior,10,4,8,30.0,196,...,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders

In [6]:
df.groupby('product_name')

In [7]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [8]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [9]:
df.groupby('department_id').order_number.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [10]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [11]:
df_ords_merged['max_order'] = df_ords_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [12]:
df_ords_merged.head(15)

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,0,2539329,1,prior,1,2,8,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,10
1,1,1,2398795,1,prior,2,3,7,15.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,2,2,473747,1,prior,3,3,12,21.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,3,3,2254736,1,prior,4,4,7,29.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,4,4,431534,1,prior,5,4,15,28.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,5,5,3367565,1,prior,6,2,7,19.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,10
6,6,6,550135,1,prior,7,1,9,20.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,10
7,7,7,3108588,1,prior,8,1,14,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,8,8,2295261,1,prior,9,1,16,0.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,10
9,9,9,2550362,1,prior,10,4,8,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
10,144,144,2968173,15,prior,15,1,9,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
11,146,146,1870022,15,prior,17,2,16,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,22
12,147,147,1911383,15,prior,18,2,11,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,22
13,150,150,2715276,15,prior,21,1,9,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
14,151,151,487368,15,prior,22,1,10,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22

In [13]:
df_ords_merged.head(100)

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,0,2539329,1,prior,1,2,8,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,10
1,1,1,2398795,1,prior,2,3,7,15.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,2,2,473747,1,prior,3,3,12,21.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,3,3,2254736,1,prior,4,4,7,29.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,4,4,431534,1,prior,5,4,15,28.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5895,5895,3226575,360,prior,1,5,12,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,3
96,6137,6137,1469869,377,prior,3,5,17,3.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,3
97,6259,6259,1927023,387,prior,2,4,10,22.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,6740,6740,858092,420,prior,4,1,19,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,6741,6741,119314,420,prior,5,3,19,16.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22

In [14]:
pd.options.display.max_rows = None

In [15]:
df_ords_merged.head(100)

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,0,2539329,1,prior,1,2,8,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,10
1,1,1,2398795,1,prior,2,3,7,15.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,2,2,473747,1,prior,3,3,12,21.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,3,3,2254736,1,prior,4,4,7,29.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,4,4,431534,1,prior,5,4,15,28.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,5,5,3367565,1,prior,6,2,7,19.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,10
6,6,6,550135,1,prior,7,1,9,20.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,10
7,7,7,3108588,1,prior,8,1,14,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,8,8,2295261,1,prior,9,1,16,0.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,10
9,9,9,2550362,1,prior,10,4,8,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
10,144,144,2968173,15,prior,15,1,9,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
11,146,146,1870022,15,prior,17,2,16,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,22
12,147,147,1911383,15,prior,18,2,11,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,22
13,150,150,2715276,15,prior,21,1,9,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
14,151,151,487368,15,prior,22,1,10,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,209,209,2293453,19,prior,2,5,14,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,9
16,212,212,1973799,19,prior,5,6,12,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,9
17,214,214,532817,19,prior,7,4,17,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,9
18,232,232,1573906,21,prior,10,3,10,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33
19,458,458,1593000,31,prior,10,3,8,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,20
20,465,465,2231262,31,prior,17,3,11,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
21,617,617,2580647,43,prior,6,4,16,4.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,11
22,620,620,2187180,43,prior,9,4,12,3.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
23,751,751,2497897,52,prior,1,1,9,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,27
24,752,752,1318871,52,prior,2,1,10,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,753,753,1261384,52,prior,3,1,10,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,755,755,580568,52,prior,5,2,10,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,27
27,757,757,2428073,52,prior,7,2,7,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,27
28,759,759,342306,52,prior,9,1,11,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,760,760,1520353,52,prior,10,2,10,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,27
30,761,761,2542086,52,prior,11,2,9,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,27
31,762,762,944694,52,prior,12,1,16,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,27
32,765,765,1268191,52,prior,15,2,11,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,27
33,767,767,1122089,52,prior,17,2,10,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,27
34,768,768,1498922,52,prior,18,2,10,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,27
35,769,769,180919,52,prior,19,3,8,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,27
36,771,771,2695875,52,prior,21,5,10,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,27
37,1022,1022,3205960,67,prior,1,3,11,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
38,1023,1023,970922,67,prior,2,1,15,5.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,1024,1024,596585,67,prior,3,1,13,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,1025,1025,2037087,67,prior,4,2,9,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,24
41,1026,1026,2474111,67,prior,5,3,14,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
42,1027,1027,1568481,67,prior,6,3,12,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
43,1029,1029,2048527,67,prior,8,2,11,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,24
44,1030,1030,2389031,67,prior,9,2,14,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,24
45,1031,1031,2378562,67,prior,10,1,10,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1032,1032,1515698,67,prior,11,1,11,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1033,1033,1928050,67,prior,12,2,12,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,24
48,1034,1034,1949274,67,prior,13,1,10,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,1035,1035,551869,67,prior,14,1,9,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,24
50,1037,1037,768572,67,prior,16,4,10,9.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,24
51,1039,1039,150528,67,prior,18,5,16,4.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,24
52,1040,1040,29758,67,prior,19,0,14,9.0,196,...,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1042,1042,1558976,67,prior,21,1,9,5.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,24
54,1043,1043,863974,67,prior,22,1,11,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,1044,1044,2308399,67,prior,23,1,14,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,1202,1202,2759128,81,prior,3,1,9,14.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,7
57,1204,1204,1812985,81,prior,5,2,20,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,7
58,1208,1208,1889835,82,prior,1,3,15,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,19
59,1210,1210,499460,82,prior,3,5,10,5.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,19
60,1211,1211,2728456,82,prior,4,0,11,16.0,196,...,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19
61,1213,1213,2653743,82,prior,6,4,9,13.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,19
62,1216,1216,1358880,82,prior,9,1,10,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,1217,1217,343588,82,prior,10,2,11,1.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,19
64,1222,1222,3034663,82,prior,15,2,11,12.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,19
65,1225,1225,147262,82,prior,18,1,13,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,1226,1226,3144004,82,prior,19,2,15,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,19
67,1480,1480,2126069,98,prior,3,0,9,25.0,196,...,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Average orders,14
68,1484,1484,2210120,98,prior,7,5,14,5.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,14
69,1486,1486,681011,98,prior,9,3,9,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,14
70,1488,1488,2846344,98,prior,11,4,13,15.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
71,1489,1489,747431,98,prior,12,6,13,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,14
72,1490,1490,2383054,98,prior,13,4,11,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
73,1491,1491,1993729,98,prior,14,5,8,8.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,14
74,1608,1608,1403849,109,prior,3,3,17,9.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,6
75,1744,1744,520620,120,prior,1,3,11,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
76,1746,1746,3273029,120,prior,3,2,8,19.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,3
77,2781,2781,1861943,185,prior,2,1,12,25.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2891,2891,2040988,195,prior,1,1,14,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,2898,2898,1680569,195,prior,8,1,9,4.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,58
80,2909,2909,276171,195,prior,19,5,11,3.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,58
81,2912,2912,2744976,195,prior,22,5,10,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,58
82,2915,2915,2781919,195,prior,25,1,14,4.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,2921,2921,1738718,195,prior,31,2,8,4.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,58
84,2924,2924,3058369,195,prior,34,3,10,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
85,2927,2927,1485596,195,prior,37,2,15,0.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,58
86,2930,2930,417035,195,prior,40,3,16,2.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,58
87,2937,2937,1615297,195,prior,47,5,10,2.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,58
88,2942,2942,1765587,195,prior,52,3,12,2.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
89,2947,2947,745908,195,prior,57,4,11,3.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,58
90,3451,3451,2505656,222,prior,17,2,12,1.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,70
91,3472,3472,3268370,222,prior,38,5,15,1.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,70
92,4667,4667,2016711,290,prior,9,5,19,6.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,51
93,4686,4686,2706088,290,prior,28,6,10,7.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,51
94,5551,5551,1952286,331,prior,6,5,16,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,8
95,5895,5895,3226575,360,prior,1,5,12,NaN,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Most orders,3
96,6137,6137,1469869,377,prior,3,5,17,3.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly days,Average orders,3
97,6259,6259,1927023,387,prior,2,4,10,22.0,196,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,6740,6740,858092,420,prior,4,1,19,30.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,6741,6741,119314,420,prior,5,3,19,16.0,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,22

In [16]:
df_ords_merged.loc[df_ords_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [17]:
df_ords_merged.loc[(df_ords_merged['max_order'] <= 40) & (df_ords_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [18]:
df_ords_merged.loc[df_ords_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [19]:
df_ords_merged['loyalty_flag'].value_counts(dropna = False)

Regular customer    15877395
Loyal customer      10284396
New customer         6244250
Name: loyalty_flag, dtype: int64

In [21]:
df_ords_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3